# Generated by Django 4.2.10 on 2024-02-19 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Forum',
            fields=[
                ('name', models.CharField(max_length=25)),
                ('dob', models.DateField(auto_now_add=True)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('F', 'Female'), ('M', 'Male'), ('O', 'Other')], max_length=10)),
                ('phoneno', models.IntegerField(max_length=10)),
                ('email', models.EmailField(max_length=20, primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=100)),
                ('district', models.CharField(choices=[('Idukki', 'Idukki'), ('Kottayam', 'Kottayam'), ('Kollam', 'Kollam'), ('Trissur', 'Trissur'), ('Eranakulam', 'Eranakulam')], max_length=50)),
                ('branch', models.CharField(max_length=50)),
                ('accounttype', models.CharField(choices=[('S', 'Savings Account'), ('C', 'Current Account')], max_length=10)),
                ('material', models.CharField(choices=[('Debit', 'Debit Card'), ('Credit', 'Credit Card'), ('Cheque', 'Through Cheque')], max_length=50)),
            ],
        ),
    ]
