# Generated by Django 4.2.10 on 2024-02-20 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0002_alter_forum_phoneno'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(max_length=250)),
                ('district', models.CharField(choices=[('Idukki', 'Idukki'), ('Kottayam', 'Kottayam'), ('Kollam', 'Kollam'), ('Vayanad', 'Vayanad'), ('Eranakulam', 'Eranakulam')], max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=250)),
                ('password', models.CharField(max_length=250)),
            ],
        ),
        migrations.AlterField(
            model_name='forum',
            name='district',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='forum',
            name='material',
            field=models.CharField(max_length=50),
        ),
    ]
