# Generated by Django 4.2.10 on 2024-02-20 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0003_branches_register_alter_forum_district_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum',
            name='dob',
            field=models.DateField(null=True),
        ),
    ]
