# Generated by Django 4.2.10 on 2024-02-21 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0004_alter_forum_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='forum',
            name='username',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='forum',
            name='address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='forum',
            name='branch',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='forum',
            name='district',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='forum',
            name='gender',
            field=models.CharField(choices=[('F', 'Female'), ('M', 'Male'), ('O', 'Other')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='forum',
            name='phoneno',
            field=models.IntegerField(null=True),
        ),
    ]
